# Find all the available rules by running:
# swiftlint rules
# https://realm.github.io/SwiftLint/ to look up what they do

analyzer_rules: # rules used only by 'swiftlint analyze'
  - unused_declaration
  - unused_import

disabled_rules: # rule identifiers to exclude from running
  - line_length
  - nesting

opt_in_rules: # some rules are only opt-in
  - empty_collection_literal # Prefer checking isEmpty over comparing to an empty collection.
  - empty_count # Prefer checking isEmpty over comparing count to zero.
  - empty_string # Prefer checking isEmpty over comparing string to an empty string literal.
  - expiring_todo # TODOs and FIXMEs should be resolved prior to their expiry date.
  - overridden_super_call # Some overridden methods should always call super
  - toggle_bool # Prefer someBool.toggle() over someBool = !someBool.
  - vertical_parameter_alignment # Function parameters should be aligned vertically if they’re in multiple lines in a declaration.
  - vertical_parameter_alignment_on_call # Function parameters should be aligned vertically if they’re in multiple lines in a method call.
  - vertical_whitespace_closing_braces # Don’t include (empty line) before closing braces.
  - yoda_condition # Variable should be placed on the left, the constant on the right of a comparison operator.

included: # paths to include during linting. `--path` is ignored if present.
  - Hymns
  - HymnsTests
  - HymnsSnapshotTests
  - HymnsUITests

function_body_length: # 
 - 200 # warning if function has < 200 lines
 - 300 # error if function has < 300 lines

file_length:
  warning: 550
  error: 800

# Change from an error to a warning by using the warning flag.
type_name:
  min_length: 3 # only warning
  max_length: # warning and error
    warning: 30
    error: 35
  excluded:
    # We need to exclude these names from the linter because it does not like the _ being nonalphanumeric
    - HymnalApiService_GetHymnTest
    - HymnalApiService_GetHymnSpec
    - HymnalApiService_SearchTest
    - HymnsRepositoryImpl_dbInitialized_dbHitTests
    - HymnsRepositoryImpl_dbInitialized_dbMissTests
    - HymnsRepositoryImpl_dbUninitializedTests
    - HymnDataStoreGrdbImpl_BrowseSpec

# https://stackoverflow.com/questions/39665790/swiftlint-exclude-file-for-specific-rule
identifier_name:
  min_length: # only min_length
    error: 2 # only error
  excluded: # excluded via string array
    - id
    - up

large_tuple:
   - 3 # warn user when using 3 values in tuple
   - 4 # give error if there are 4
