name: Build and Test iOS 17 & iOS 18

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: See All Xcode Versions
      run: ls -n /Applications/ | grep Xcode*
    - name: Set Xcode Version
      run: sudo xcode-select -s /Applications/Xcode_16.1.app
    - name: Shut down simulators
      run: xcrun simctl shutdown all
    - name: Reset simulators
      run: xcrun simctl erase all
    - name: Clean Build Test
      run: |
        xcodebuild clean build test \
          -project Hymns.xcodeproj \
          -scheme Hymns \
          -destination "platform=iOS Simulator,name=iPhone 15 Pro,OS=17.5" \
          -destination "platform=iOS Simulator,name=iPhone 16 Pro,OS=18.1"
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: Test Logs
        path: /Users/runner/Library/Developer/Xcode/DerivedData/Hymns-*/Logs
        retention-days: 5
    - name: Download all workflow run artifacts
      uses: actions/download-artifact@v4
