name: Danger
on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: "Run Danger"
    steps:
      - uses: actions/checkout@v2
      - name: Danger
        uses: docker://ghcr.io/danger/danger-swift-with-swiftlint:3.10.1
        with:
            args: --failOnErrors --no-publish-check
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
