name: "Danger Swift"
on: [pull_request]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Danger
    uses: danger/swift@2.0.1
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
