name: Danger
on:
  push:
    paths:
      - '**/*.swift'
  pull_request:
    paths:
      - '**/*.swift'
jobs:
  build:
    runs-on: ubuntu-latest
    name: "Run Danger"
    steps:
      - uses: actions/checkout@v2
      - name: Danger
        uses: danger/swift@3.0.0
        with:
            args: --failOnErrors --no-publish-check
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
