name: Danger
on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest
    name: "Run Danger"
    steps:
      - uses: actions/checkout@v2
      - name: Dependencies
        run: |
          pod deintegrate
          pod install
      - name: Run coverage
        run: xcodebuild test -scheme Hymns -derivedDataPath Build/ -enableCodeCoverage YES
      - name: Danger
        uses: f-meloni/danger-swift-swiftlint-action@0.2.8
        with:
            args: --failOnErrors --no-publish-check
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
