name: Danger
on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest
    name: "Run Danger"
    steps:
      - uses: actions/checkout@v2
      - name: Dependencies
        run: |
          pod deintegrate
          pod install
      - name: Run coverage
        run: xcodebuild test -workspace Hymns.xcworkspace -scheme Hymns -destination "platform=iOS Simulator,name=iPhone 11 Pro" -derivedDataPath Build/ -enableCodeCoverage YES
      - name: Danger
        uses: danger/swift@3.0.0
        with:
            args: --failOnErrors --no-publish-check
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
