# https://github.com/marketplace/actions/remove-artifacts
name: Remove old artifacts

on:
  schedule:
    # Every day at 8 am UTC/1 am PST
    - cron: '0 8 * * *'

jobs:
  remove-old-artifacts:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - name: Remove old artifacts
      uses: c-hive/gha-remove-artifacts@v1.2.0
      with:
        age: '0 days'
        # Optional inputs
        # skip-tags: true
        skip-recent: 5
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
