name: Swift

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Dependencies
      run: pod install
    - name: Generate XCode Proj 
      run: |
        swift package init --type library
        swift package generate-xcodeproj
    - name: SwiftLint
      run: ./Pods/SwiftLint/swiftlint
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
