name: Swift

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    # https://medium.com/xcblog/xcodebuild-deploy-ios-app-from-command-line-c6defff0d8b8
    steps:
    - uses: actions/checkout@v2

    - name Static Aanlysis
      run: xcodebuild -project Hymns.xcodeproj -scheme Hymns -sdk iphoneos clean analyze
    - name: Build for Testing
      run: xcodebuild build-for-testing -workspace Hymns.xcodeproj/project.xcworkspace -scheme Hymns -destination "platform=iOS Simulator,name=iPhone 11 Pro"
    - name: Test with MasterTestPlan
      run: xcodebuild test-without-building -workspace Hymns.xcodeproj/project.xcworkspace -scheme Hymns -destination "platform=iOS Simulator,name=iPhone 11 Pro" -testPlan MasterTestPlan
