name: Swift

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    # https://medium.com/xcblog/xcodebuild-deploy-ios-app-from-command-line-c6defff0d8b8
    steps:
    - uses: actions/checkout@v2
    - name: Install xcpretty
      run: gem install xcpretty
    - name: Install xcpretty-json-formatter
      run: gem install xcpretty-json-formatter
    - name: Dependencies
      run: |
        pod deintegrate
        pod install
    - name: Generate Mockingbird Mocks
      run: Pods/MockingbirdFramework/mockingbird generate --targets 'Hymns'  --outputs 'MockingbirdMocks/HymnsMocks.generated.swift' --disable-swiftlint
    - name: Build and test
      run: xcodebuild test -workspace Hymns.xcworkspace -scheme Hymns -destination "platform=iOS Simulator,name=iPhone 11 Pro" -testPlan MasterTestPlan | XCPRETTY_JSON_FILE_OUTPUT=result.json xcpretty -f `xcpretty-json-formatter`
